version: '3.8'

services:
  ml:
    build:
      context: .
      dockerfile: ml/Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    environment:
      - ML_API_URL=http://ml:8001
    depends_on:
      - ml
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - gateway
    restart: unless-stopped